### ISSUE TITLE
请问是否有依赖版本要求，打开markdown转图之后，报错

### ISSUE THREAD

**Issue by misaka10032w** [araea/koishi-plugin-message-counter#8]
`2024-06-16 23:23:21 [W] command messagecounter.群排行榜 
                        TypeError: browser.createBrowserContext is not a function
                            at generateRankingChartStyle3 (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-message-counter\lib\index.js:1223:39)
                            at async LeaderboardToHorizontalBarChartConversion (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-message-counter\lib\index.js:1814:20)
                            at async Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-message-counter\lib\index.js:591:33)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1151:14)
                            at async Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1165:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2184:22
                            at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2087:22)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:890:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:890:16)
                            at async Processor._handleMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:901:22)`

koishi版本：4.17.8
canvas：0.2.2
message-counter：2.0.8
markdown-to-image-service：1.1.9
@seidko/puppeteer：3.5.1
puppeteer：3.8.4
chrome： 109.0.5414.168
系统：server 2012 R2

**Comment by araea** [comment]
# 用跟楼楼相同的版本测试，无报错
![image](https://github.com/araea/koishi-plugin-message-counter/assets/120614554/c945f0c1-7aa5-4578-b3b1-0f925503b09b)

**Comment by araea** [comment]
```markdown
# 2.0.9 已修复该问题！
```

**Comment by misaka10032w** [comment]
所以是咋回事，好奇，以为是浏览器版本低，就把系统2012升级2022装新浏览器了

**Comment by araea** [comment]
> 所以是咋回事，好奇，以为是浏览器版本低，就把系统2012升级2022装新浏览器了

之前插件没有显式注册pptr插件，所以可能会没有pptr的方法。
